Add support for SPM Packages

diff --git a/.github/workflows/pull-request-tests.yml b/.github/workflows/pull-request-tests.yml
--- a/.github/workflows/pull-request-tests.yml
+++ b/.github/workflows/pull-request-tests.yml
@@ -26,7 +26,7 @@ jobs:
             action: build
             use-xcpretty: false
     steps:
-      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
+      - run: sudo xcode-select -s /Applications/Xcode_12.0.app/Contents/Developer
       - name: Install dependencies
         run: sudo npm i -g @zeit/ncc typescript
       - uses: actions/checkout@v2
@@ -64,7 +64,7 @@ jobs:
             action: build
             use-xcpretty: false
     steps:
-      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
+      - run: sudo xcode-select -s /Applications/Xcode_12.0.app/Contents/Developer
       - name: Install dependencies
         run: sudo npm i -g @zeit/ncc typescript
       - uses: actions/checkout@v2
@@ -81,6 +81,42 @@ jobs:
           use-xcpretty: ${{matrix.use-xcpretty}}
       - name: Check for derived data
         run: ls ~/Library/Developer/Xcode/DerivedData/ | grep -q '^TestProject.*'
+
+  test-package:
+    runs-on: macos-latest
+    strategy:
+      matrix:
+        destination:
+          - platform=macOS
+          - platform=iOS Simulator,OS=latest,name=iPhone 11
+          - platform=tvOS Simulator,OS=latest,name=Apple TV 4K
+        action: [ test ]
+        use-xcpretty: [ true, false ]
+        include:
+          - destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm
+            skip-testing: ''
+            action: build
+            use-xcpretty: true
+          - destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm
+            skip-testing: ''
+            action: build
+            use-xcpretty: false
+    steps:
+      - run: sudo xcode-select -s /Applications/Xcode_12.0.app/Contents/Developer
+      - name: Install dependencies
+        run: sudo npm i -g @zeit/ncc typescript
+      - uses: actions/checkout@v2
+      - name: Generate action code
+        run: npm run deploy
+      - uses: './'
+        with:
+          spm-package: __test__/TestPackage
+          destination: ${{matrix.destination}}
+          skip-testing: ${{matrix.skip-testing}}
+          action: ${{matrix.action}}
+          use-xcpretty: ${{matrix.use-xcpretty}}
+      - name: Check for derived data
+        run: ls ~/Library/Developer/Xcode/DerivedData/ | grep -q '^TestPackage.*'
 
   test-dry-run-project:
     needs: deploy-action-code
@@ -170,6 +206,53 @@ jobs:
           if [ "${{matrix.use-xcpretty}}" == "true" ]; then
             EXPECTED_COMMAND="${EXPECTED_COMMAND} | xcpretty"
           fi
+          if [ "${EXPECTED_COMMAND}" != "${{steps.xcodebuild.outputs.executed-command}}" ]; then
+            printf "::error::Executed command did not match expectations!\nExecuted: ${{steps.xcodebuild.outputs.executed-command}}\nExpected: ${EXPECTED_COMMAND}\n"
+            exit 1
+          fi
+
+  test-dry-run-package:
+    needs: deploy-action-code
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        spm-package: [ /path/to/TestPackage ]
+        destination:
+          - platform=macOS
+          - platform=iOS Simulator,OS=latest,name=iPhone 11
+          - platform=tvOS Simulator,OS=latest,name=Apple TV 4K
+        configuration: [ Debug, Release ]
+        sdk: [ SDK1, SDK2 ]
+        skip-testing: [ 'Test/Skip' ]
+        build-settings: [ 'ABC=DEF' ]
+        action: [ build, test ]
+        use-xcpretty: [ true, false ]
+    steps:
+      - run: test "${{secrets.ACTIONS_STEP_DEBUG}}" == "true"
+      - name: Install dependencies
+        run: sudo npm i -g @zeit/ncc typescript
+      - uses: actions/checkout@v2
+      - name: Generate action code
+        run: npm run deploy
+      - uses: './'
+        with:
+          spm-package: ${{matrix.spm-package}}
+          destination: ${{matrix.destination}}
+          configuration: ${{matrix.configuration}}
+          sdk: ${{matrix.sdk}}
+          skip-testing: ${{matrix.skip-testing}}
+          build-settings: ${{matrix.build-settings}}
+          action: ${{matrix.action}}
+          use-xcpretty: ${{matrix.use-xcpretty}}
+          dry-run: true
+        id: xcodebuild
+      - name: Check executed command
+        run: |
+          EXPECTED_COMMAND="pushd ${{matrix.spm-package}} && xcodebuild -destination ${{matrix.destination}} -configuration ${{matrix.configuration}} -sdk ${{matrix.sdk}} -skip-testing ${{matrix.skip-testing}} ${{matrix.build-settings}} ${{matrix.action}}"
+          if [ "${{matrix.use-xcpretty}}" == "true" ]; then
+            EXPECTED_COMMAND="${EXPECTED_COMMAND} | xcpretty"
+          fi
+          EXPECTED_COMMAND="${EXPECTED_COMMAND} ; popd"
           if [ "${EXPECTED_COMMAND}" != "${{steps.xcodebuild.outputs.executed-command}}" ]; then
             printf "::error::Executed command did not match expectations!\nExecuted: ${{steps.xcodebuild.outputs.executed-command}}\nExpected: ${EXPECTED_COMMAND}\n"
             exit 1
