Add more tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -679,3 +679,119 @@ jobs:
             printf "::error::Executed command did not match expectations!\nExecuted: ${ACTUAL_COMMAND}\nExpected: ${EXPECTED_COMMAND}\n"
             exit 1
           fi
+
+  test-dry-run-basic:
+    name: Dry Run Basic Build
+    runs-on: ubuntu-latest
+    env:
+      INPUT_SCHEME: TestScheme
+    steps:
+      - if: ${{ github.event_name == 'pull_request' && env.RUNNER_DEBUG != 1 }}
+        run: echo 'RUNNER_DEBUG=1' >> "${GITHUB_ENV}"
+      - if: ${{ github.event_name == 'pull_request' }}
+        run: test "${RUNNER_DEBUG}" == "1"
+      - if: ${{ github.event_name == 'push' }}
+        env:
+          DEBUG_ENABLED: ${{ secrets.ACTIONS_STEP_DEBUG }}
+        run: test "${DEBUG_ENABLED}" == 'true'
+      - uses: actions/checkout@v3
+      - name: Generate action code
+        if: ${{ github.event_name == 'pull_request' }}
+        uses: ./.github/actions/generate-action-code
+      - uses: sersoft-gmbh/xcodebuild-action@master
+        if: ${{ github.event_name == 'push' }}
+        id: xcodebuild-master
+        with:
+          scheme: ${{ env.INPUT_SCHEME }}
+          dry-run: true
+      - uses: './'
+        if: ${{ github.event_name == 'pull_request' }}
+        id: xcodebuild-local
+        with:
+          scheme: ${{ env.INPUT_SCHEME }}
+          dry-run: true
+      - id: xcodebuild
+        env:
+          EVENT_NAME: ${{ github.event_name }}
+          BRANCH_UNPROCESSED_COMMAND: ${{ steps.xcodebuild-master.outputs.unprocessed-command }}
+          BRANCH_EXECUTED_COMMAND: ${{ steps.xcodebuild-master.outputs.executed-command }}
+          LOCAL_UNPROCESSED_COMMAND: ${{ steps.xcodebuild-local.outputs.unprocessed-command }}
+          LOCAL_EXECUTED_COMMAND: ${{ steps.xcodebuild-local.outputs.executed-command }}
+        run: |
+          if [ "${EVENT_NAME}" == 'push' ]; then
+            echo "unprocessed-command=${BRANCH_UNPROCESSED_COMMAND}" >> "${GITHUB_OUTPUT}"
+            echo "executed-command=${BRANCH_EXECUTED_COMMAND}" >> "${GITHUB_OUTPUT}"
+          else
+            echo "unprocessed-command=${LOCAL_UNPROCESSED_COMMAND}" >> "${GITHUB_OUTPUT}"
+            echo "executed-command=${LOCAL_EXECUTED_COMMAND}" >> "${GITHUB_OUTPUT}"
+          fi
+      - name: Check executed command
+        env:
+          UNPROCESSED_COMMAND: ${{ steps.xcodebuild.outputs.unprocessed-command }}
+          EXECUTED_COMMAND: ${{ steps.xcodebuild.outputs.executed-command }}
+        run: |
+          EXPECTED_COMMAND="xcodebuild -scheme ${INPUT_SCHEME} | xcpretty --color"
+          ACTUAL_COMMAND="${UNPROCESSED_COMMAND}"
+          if [ "${EXPECTED_COMMAND}" != "${ACTUAL_COMMAND}" ]; then
+            printf "::error::Executed command did not match expectations!\nExecuted: ${ACTUAL_COMMAND}\nExpected: ${EXPECTED_COMMAND}\n"
+            exit 1
+          fi
+
+  test-dry-run-deprecated-args:
+    name: Dry Run Deprecated Args
+    runs-on: ubuntu-latest
+    env:
+      INPUT_SCHEME: TestScheme
+    steps:
+      - if: ${{ github.event_name == 'pull_request' && env.RUNNER_DEBUG != 1 }}
+        run: echo 'RUNNER_DEBUG=1' >> "${GITHUB_ENV}"
+      - if: ${{ github.event_name == 'pull_request' }}
+        run: test "${RUNNER_DEBUG}" == "1"
+      - if: ${{ github.event_name == 'push' }}
+        env:
+          DEBUG_ENABLED: ${{ secrets.ACTIONS_STEP_DEBUG }}
+        run: test "${DEBUG_ENABLED}" == 'true'
+      - uses: actions/checkout@v3
+      - name: Generate action code
+        if: ${{ github.event_name == 'pull_request' }}
+        uses: ./.github/actions/generate-action-code
+      - uses: sersoft-gmbh/xcodebuild-action@master
+        if: ${{ github.event_name == 'push' }}
+        id: xcodebuild-master
+        with:
+          scheme: ${{ env.INPUT_SCHEME }}
+          use-xcpretty: true
+          dry-run: true
+      - uses: './'
+        if: ${{ github.event_name == 'pull_request' }}
+        id: xcodebuild-local
+        with:
+          scheme: ${{ env.INPUT_SCHEME }}
+          use-xcpretty: true
+          dry-run: true
+      - id: xcodebuild
+        env:
+          EVENT_NAME: ${{ github.event_name }}
+          BRANCH_UNPROCESSED_COMMAND: ${{ steps.xcodebuild-master.outputs.unprocessed-command }}
+          BRANCH_EXECUTED_COMMAND: ${{ steps.xcodebuild-master.outputs.executed-command }}
+          LOCAL_UNPROCESSED_COMMAND: ${{ steps.xcodebuild-local.outputs.unprocessed-command }}
+          LOCAL_EXECUTED_COMMAND: ${{ steps.xcodebuild-local.outputs.executed-command }}
+        run: |
+          if [ "${EVENT_NAME}" == 'push' ]; then
+            echo "unprocessed-command=${BRANCH_UNPROCESSED_COMMAND}" >> "${GITHUB_OUTPUT}"
+            echo "executed-command=${BRANCH_EXECUTED_COMMAND}" >> "${GITHUB_OUTPUT}"
+          else
+            echo "unprocessed-command=${LOCAL_UNPROCESSED_COMMAND}" >> "${GITHUB_OUTPUT}"
+            echo "executed-command=${LOCAL_EXECUTED_COMMAND}" >> "${GITHUB_OUTPUT}"
+          fi
+      - name: Check executed command
+        env:
+          UNPROCESSED_COMMAND: ${{ steps.xcodebuild.outputs.unprocessed-command }}
+          EXECUTED_COMMAND: ${{ steps.xcodebuild.outputs.executed-command }}
+        run: |
+          EXPECTED_COMMAND="xcodebuild -scheme ${INPUT_SCHEME} | xcpretty --color"
+          ACTUAL_COMMAND="${UNPROCESSED_COMMAND}"
+          if [ "${EXPECTED_COMMAND}" != "${ACTUAL_COMMAND}" ]; then
+            printf "::error::Executed command did not match expectations!\nExecuted: ${ACTUAL_COMMAND}\nExpected: ${EXPECTED_COMMAND}\n"
+            exit 1
+          fi
